# Managed PostgreSQL, zone-redundant HA, VNet-injected (private, no public access).
# Zone-redundant HA gives the active-passive failover the design calls for: a
# synchronous standby in a second zone that Azure promotes on failure. Mirrors
# aws-scp-governance/workload/rds.tf (Multi-AZ Postgres, CMK, managed credential).
#
# The admin credential is generated by Terraform and stored in the workload Key
# Vault, which the External Secrets Operator identity reads over workload identity,
# the sanctioned secrets path. Storage is CMK-encrypted with the data-tier key.

resource "azurerm_user_assigned_identity" "pg" {
  name                = "id-${var.project}-postgres"
  location            = azurerm_resource_group.prod.location
  resource_group_name = azurerm_resource_group.prod.name
  tags                = local.tags
}

# The server identity uses the data CMK to encrypt storage.
resource "azurerm_role_assignment" "pg_kms" {
  scope                = azurerm_key_vault.workload.id
  role_definition_name = "Key Vault Crypto User"
  principal_id         = azurerm_user_assigned_identity.pg.principal_id
}

# Private DNS for the flexible server's VNet-injected endpoint.
resource "azurerm_private_dns_zone" "pg" {
  name                = "${var.project}-prod.postgres.database.azure.com"
  resource_group_name = azurerm_resource_group.prod.name
  tags                = local.tags
}

resource "azurerm_private_dns_zone_virtual_network_link" "pg" {
  name                  = "pg-to-prod"
  resource_group_name   = azurerm_resource_group.prod.name
  private_dns_zone_name = azurerm_private_dns_zone.pg.name
  virtual_network_id    = azurerm_virtual_network.prod.id
  registration_enabled  = false
  tags                  = local.tags
}

resource "random_password" "pg" {
  length           = 24
  special          = true
  override_special = "!#%*-_"
}

# The deployer needs secrets-officer rights to write the credential on first apply.
resource "azurerm_role_assignment" "kv_deployer_secrets" {
  scope                = azurerm_key_vault.workload.id
  role_definition_name = "Key Vault Secrets Officer"
  principal_id         = data.azurerm_client_config.current.object_id
}

resource "azurerm_key_vault_secret" "pg_admin" {
  # checkov:skip=CKV_AZURE_41:No static expiration on the DB credential; rotation is handled operationally (the ESO workload identity reads the current value), not by a fixed expiry.
  name         = "postgres-admin-password"
  value        = random_password.pg.result
  key_vault_id = azurerm_key_vault.workload.id
  content_type = "text/plain"

  depends_on = [azurerm_role_assignment.kv_deployer_secrets]
}

resource "azurerm_postgresql_flexible_server" "prod" {
  # checkov:skip=CKV_AZURE_136:Server geo-redundant backup is a cost add; cross-region protection is provided by the geo-redundant Backup vault (backup.tf).
  # checkov:skip=CKV2_AZURE_57:The server is VNet-injected into a delegated subnet with a private DNS zone (no public access), which is private without a separate private endpoint.
  name                = "psql-${var.project}-prod-${random_string.kv.result}"
  location            = azurerm_resource_group.prod.location
  resource_group_name = azurerm_resource_group.prod.name
  version             = var.pg_version
  sku_name            = var.pg_sku
  storage_mb          = var.pg_storage_mb

  # Pin the primary zone (and the standby zone below) so Terraform matches the
  # zones Azure assigns for zone-redundant HA instead of trying to unset them.
  zone = "1"

  administrator_login    = "appadmin"
  administrator_password = random_password.pg.result

  delegated_subnet_id = azurerm_subnet.data.id
  private_dns_zone_id = azurerm_private_dns_zone.pg.id

  public_network_access_enabled = false

  authentication {
    active_directory_auth_enabled = true
    password_auth_enabled         = true
    tenant_id                     = data.azurerm_client_config.current.tenant_id
  }

  high_availability {
    mode                      = "ZoneRedundant"
    standby_availability_zone = "2"
  }

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.pg.id]
  }

  customer_managed_key {
    key_vault_key_id                  = azurerm_key_vault_key.data.id
    primary_user_assigned_identity_id = azurerm_user_assigned_identity.pg.id
  }

  tags = local.tags

  depends_on = [
    azurerm_private_dns_zone_virtual_network_link.pg,
    azurerm_role_assignment.pg_kms,
  ]
}

resource "azurerm_postgresql_flexible_server_database" "app" {
  name      = "app"
  server_id = azurerm_postgresql_flexible_server.prod.id
  charset   = "UTF8"
  collation = "en_US.utf8"
}
